merge commit
2110336-2565-2/sec2-group11-trainder-backend pull request #24
Opened 2023-02-08 15:28 UTC by looknatc

filter trainer on speciality if  filter = ["a","b","c"] trainer who have speciality "a" or "b" or "c" will be selected 
route /protected/filter-trainer
update User struct to have trainerInfo filed

2023-02-08 15:29 UTC, looknatc commented
@noppakorn  review please

2023-02-08 15:45 UTC, noppakorn commented
@looknatc please resolve the conflict with #22 that just got merged into main and request review again

2023-02-09 04:08 UTC, looknatc commented
@noppakorn เสดเเล้ว

2023-02-09 05:02 UTC, noppakorn requested changes
Some change requires. The most important one is to add limit to the api response. Also, some question are asked about json tags.

2023-02-09 05:02 UTC, noppakorn commented on models/auth_model.go
> +	TraineeCount   int32    `json:"traineeCount" `
why some of it is json and some is bson do you have an explanation?

2023-02-09 05:02 UTC, noppakorn commented on models/auth_model.go
> +	TrainerInfo    TrainerInfo `bson:"trainerInfo" json:"trainerInfo"`
why does this also have json?

2023-02-09 05:02 UTC, noppakorn commented on controllers/trainer_controller.go
> +	Rating         float64  `json:"rating "`
remove space behind `rating `

2023-02-09 05:02 UTC, noppakorn commented on controllers/trainer_controller.go
> +	// Fee        float32 `json:"Fee" binding:"required"`
json field should be camelCase

2023-02-09 05:02 UTC, noppakorn commented on controllers/trainer_controller.go
> +	// Fee        float32 `json:"Fee" binding:"required"`
biding shouldn't be required for all fields because the frontend can just not put any filter and request all trainer.

2023-02-09 05:02 UTC, noppakorn commented on controllers/trainer_controller.go
> +func FilterTrainer() gin.HandlerFunc {
This function should also accept the `limit` parameter in which when the parameter is specified the api should only respond with min(len(trainerThatExistsWithFilter), limit) trainer(s).

2023-02-09 10:43 UTC, looknatc commented
@noppakorn เสด

2023-02-09 10:53 UTC, noppakorn approved these changes

2023-02-09 10:54 UTC, merged