Helper get name and role
2110336-2565-2/sec2-group11-trainder-backend pull request #67
Opened 2023-04-01 15:31 UTC by looknatc

helper API for frontend

2023-04-01 15:37 UTC, looknatc commented
@noppakorn

2023-04-01 15:50 UTC, noppakorn requested changes

2023-04-01 15:50 UTC, noppakorn commented on ws/client.go
> +			log.Printf("error adding messege to database: %v", err)
message เห้อเห้อเห้อเห้อเห้อเห้อ

2023-04-02 04:36 UTC, looknatc commented on ws/client.go
> +			log.Printf("error adding messege to database: %v", err)
merge ไปก่อน ไอแนนจะใช้ getName

2023-04-02 04:38 UTC, noppakorn approved these changes

2023-04-02 04:38 UTC, merged